config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  get '/' => 'home#index'
  get '/search' => 'users#index'
  get '/users/show' => 'users#show'
  get '/workout/new' => 'workouts#new'
  get '/trainers/inspect/:user_id' => 'users#inspect_user_workouts'
  get '/workouts/:workout_id' => 'workouts#show'
  get '/trainers/:trainer_id' => 'trainers#show'

  resources :exercises
  resources :workouts do
    resources :comments, only: [:create, :new]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability


  def initialize(user)
    # Define abilities for the passed in user here. For example:
      #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :workouts
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
  belongs_to :trainer
  has_one :exercise_type
end

app/models/exercise_type.rb
class ExerciseType < ActiveRecord::Base
  belongs_to :exercise
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :user
  belongs_to :trainer
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  belongs_to :workout
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workouts
  has_many :user_trainers
  has_many :users, through: :users_trainers
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users_trainers
  has_many :trainers, through: :users_trainers
  mount_uploader :avatar, AvatarUploader
end

app/models/users_trainer.rb
class Users_trainer < ActiveRecord::Base
  belongs_to :trainer
  belongs_to :user
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :trainer
  has_many :exercises
  has_many :comments
  has_many :sports
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @workout = Workout.find params[:workout_id]
    @comment = @workout.comments.new comment_params
    if @comment.save
      flash[:notice] = "Comment created!"
      redirect_to users_show_path(@workout)
    else
      flash[:alert] = "Comment not saved"
      redirect_to workout_path(@workout)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :workout_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :authenticate_user!

  def index
    @trainers = Trainer.all
  end

  def show #split this method
    @trained_users = fetch_trained_users
    @workouts = Workout.where("trainer_id= ?", current_trainer.id)
  end

  def inspect_user_workouts
    @workouts = Workout.where("user_id=? and trainer_id=?", params[:user_id], current_trainer.id)
  end

  private

  def fetch_trained_users
    trained_users = []
    ids = []
    fetch_user_id = Users_trainer.where("trainer_id= ?", current_trainer.id)
    fetch_user_id.each {|user| ids << user.user_id }
    ids.each {|id| trained_users << User.find(id)}
    trained_users
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @workouts = Workout.where("user_id=?", current_user.id)
    if current_user.has_role? :trainer
      @trained_users = fetch_trained_users
      @workouts_as_trainer = Workout.where("trainer_id= ?", current_user.id)
    end
  end

  def index
    @trainers = []
    all_users = User.where("id != ?", current_user.id)
    all_users.each do |user|
      if user.has_role? :trainer
        @trainers << user
      end
    end
  end

  def inspect_user_workouts
    @workouts = Workout.where("user_id=? and trainer_id=?", params[:user_id], current_user.id)
    @workout = Workout.new
  end

  private

  def fetch_trained_users
    trained_users = []
    ids = []
    fetch_user_id = Users_trainer.where("trainer_id= ?", current_user.id)
    fetch_user_id.each {|user| ids << user.user_id }
    ids.each {|id| trained_users << User.find(id)}
    trained_users
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!

  def show
    @workout= Workout.find(params[:workout_id])
    @comment = @workout.comments.new params[:comment]
  end

  def new
    @workout = Workout.new
    @trained_users = []
    ids = []
    fetch_user_id = Users_trainer.where("trainer_id= ?", current_user.id)
    fetch_user_id.each {|user| ids << user.user_id }
    ids.each {|id| @trained_users << User.find(id)}
  end

  def create
    @workout = Workout.new workout_params
      if @workout.save
        flash[:notice] = "Workout created!"
        redirect_to "/workouts/#{@workout.id}/edit"
      else
        flash[:alert] = "Workout not saved"
        render "new"
      end
  end

  def edit
    @workout = Workout.find params[:id]
    @exercise = Exercise.new
    @user = User.find @workout.user_id
  end

  def update
    @workout = Workout.find params[:id]
      if @workout.update_attributes workout_params
        redirect_to(:back)
      end
  end

  private

  def workout_params
    params.require(:workout).permit(:name, :start_time, :user_id, :trainer_id, :sport_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/edit.html.erb
<h1><%=@workout.start_time.day%>-<%=Date::MONTHNAMES[@workout.start_time.month]%></h1>
<h1><%= @user.name %></h1>

  <% @workout.exercises.each do |exercise| %>
  <div class="container add_exercises">
    <div class="col-lg-4 col-sm-6 text-center well">
        <h4><%=ExerciseType.find(exercise.exercise_type_id).name%> </h4>
          <p class="ui-state-default"><%= exercise.explanation %></p>
          <%= link_to("Delete", exercise_path(exercise), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger")%>
    </div>
  </div>
  <%end%>


<div class="edit-form">
    <%= form_for @exercise do |f| %>

      <%= f.label :type %>
      <%= f.collection_select :exercise_type_id, ExerciseType.all, :id,:name %>
      <br>
      <%= f.text_field :explanation %>
      <%= f.hidden_field :trainer_id, :value => current_user.id %>
      <%= f.hidden_field :workout_id, :value => params[:id] %>
      <br>
      <%= f.submit 'Add exercise'%>

    <%end%>
</div>

app/views/workouts/new.html.erb
<div  class="row">
  <div class="col-sm-4 workout_form" >
    <%= form_for @workout do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :date %>
      <%= f.date_field :start_time %>
      <br>
      <%= f.label :user_id %>
      <%= f.collection_select :user_id, @trained_users,:id,:name, include_blank: true %>
      <br>
      <%= f.label :sport_id %>
      <%= f.collection_select :sport_id, Sport.all, :id,:name %>

      <%= f.hidden_field :trainer_id, :value => current_user.id %>
      <br>
      <%= f.submit 'Create Workout'%>

    <%end%>
  </div>
</div>

app/views/workouts/show.html.erb
<h1><%=@workout.start_time.day%>-<%=Date::MONTHNAMES[@workout.start_time.month]%></h1>
<p><%= @workout.name %> </p>

<% @workout.exercises.each do |exercise| %>
<div class="container exercises">
  <div class="col-lg-4 col-sm-6 text-center well">
      <h4><%=ExerciseType.find(exercise.exercise_type_id).name%> </h4>
        <p class="ui-state-default"><%= exercise.explanation %></p>
  </div>
</div>
<%end%>

<h2>How did I do?</h2>
<%= form_for [@workout,@comment], url: workout_comments_path(@workout), method: "post" do |f| %>
  <%= f.label :comment %>
  <br>
  <%= f.text_area :content, :id => 'wysihtml5-textarea' %>
  <%= f.hidden_field :workout_id, :value => @workout.id %>

  <br>

  <%= f.submit 'Add comment'%>

<%end%>