config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  get '/' => 'home#index'
  get '/search' => 'users#index'
  get '/users/show' => 'users#show'
  get '/workout/new' => 'workouts#new'
  get '/trainers/inspect/:user_id' => 'users#inspect_user_workouts'
  get '/workouts/:workout_id' => 'workouts#show'
  get '/trainers/:trainer_id' => 'trainers#show'

  resources :exercises
  resources :workouts do
    resources :comments, only: [:create, :new]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability


  def initialize(user)
    # Define abilities for the passed in user here. For example:
      #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :workouts
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
  belongs_to :trainer
  has_one :exercise_type
end

app/models/exercise_type.rb
class ExerciseType < ActiveRecord::Base
  belongs_to :exercise
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :user
  belongs_to :trainer
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  belongs_to :workout
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workouts
  has_many :user_trainers
  has_many :users, through: :users_trainers
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users_trainers
  has_many :trainers, through: :users_trainers
  mount_uploader :avatar, AvatarUploader
end

app/models/users_trainer.rb
class Users_trainer < ActiveRecord::Base
  belongs_to :trainer
  belongs_to :user
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :trainer
  has_many :exercises
  has_many :comments
  has_many :sports
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @workout = Workout.find params[:workout_id]
    @comment = @workout.comments.new comment_params
    if @comment.save
      flash[:notice] = "Comment created!"
      redirect_to users_show_path(@workout)
    else
      flash[:alert] = "Comment not saved"
      redirect_to workout_path(@workout)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :workout_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :authenticate_user!

  def index
    @trainers = Trainer.all
  end

  def show #split this method
    @trained_users = fetch_trained_users
    @workouts = Workout.where("trainer_id= ?", current_trainer.id)
  end

  def inspect_user_workouts
    @workouts = Workout.where("user_id=? and trainer_id=?", params[:user_id], current_trainer.id)
  end

  private

  def fetch_trained_users
    trained_users = []
    ids = []
    fetch_user_id = Users_trainer.where("trainer_id= ?", current_trainer.id)
    fetch_user_id.each {|user| ids << user.user_id }
    ids.each {|id| trained_users << User.find(id)}
    trained_users
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @workouts = Workout.where("user_id=?", current_user.id)
    if current_user.has_role? :trainer
      @trained_users = fetch_trained_users
      @workouts_as_trainer = Workout.where("trainer_id= ?", current_user.id)
    end
  end

  def index
    @trainers = []
    all_users = User.where("id != ?", current_user.id)
    all_users.each do |user|
      if user.has_role? :trainer
        @trainers << user
      end
    end
  end

  def inspect_user_workouts
    @workouts = Workout.where("user_id=? and trainer_id=?", params[:user_id], current_user.id)
    @workout = Workout.new
  end

  private

  def fetch_trained_users
    trained_users = []
    ids = []
    fetch_user_id = Users_trainer.where("trainer_id= ?", current_user.id)
    fetch_user_id.each {|user| ids << user.user_id }
    ids.each {|id| trained_users << User.find(id)}
    trained_users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/home/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    	  <div class="modal-dialog">
				<div class="loginmodal-container">
					<h1>Login to Your Account</h1><br>
            <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

              <div><%= f.label :email %><br>

              <%= f.email_field :email, :autofocus => true %></div>

              <div><%= f.label :password %><br>

              <%= f.password_field :password %></div>

              <% if devise_mapping.rememberable? -%>

                <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>

            <% end -%>

            <%= f.submit "Sign in", :class => 'btn btn-small btn-success' %>
            <% end %>

				</div>
			  </div>
</div>

app/views/home/_sign_up_modal.html.erb
<div class="modal fade" id="sign_up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    	  <div class="modal-dialog">
				<div class="loginmodal-container">
					<h1>Create account</h1><br>
          <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>

          <%= devise_error_messages! %>

          <div><%= f.label :name %><br />

          <%= f.text_field :name %></div>

          <div><%= f.label :email %><br />

          <%= f.email_field :email, :autofocus => true %></div>

          <div><%= f.label :password %><br />

          <%= f.password_field :password %></div>

          <div><%= f.label :password_confirmation %><br />

          <%= f.password_field :password_confirmation %></div>

          <%= f.label :avatar %>
          <%= f.file_field :avatar %>

          <p><div><%= f.submit "Sign up", :class => 'btn btn-small btn-success' %></div></p>

          <% end %>
				</div>
			</div>
</div>

app/views/home/index.html.erb
  <div id="header">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<h1>Find your best online personal trainer</h1>
					<h2 class="subtitle">"No pain no gain"</h2>
          <%= form_tag("/search", method: "get") do %>
          <%= text_field_tag :q %>
          <%= submit_tag "Search", class: "button btn", id: "search_button" %>
          <% end %>
				</div>
			</div>
		</div>
	</div>



  <%= render "home/login_modal" %>
  <%= render "home/sign_up_modal" %>